version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip"
      - "unzip terraform_0.12.18_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"

  pre_build:
    commands:
      - export TF_IN_AUTOMATION=true
      - export TF_WORKSPACE=preprod
      - terraform init -input=false


  build:
    commands:
      - terraform $TF_COMMAND -var-file=variables/preprod.tfvars -auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed.